### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by feuerbach** [reynir/Verified#3]
```
% idris --install verified.ipkg 
Type checking ./Verified/Functor.idr
Type checking ./Verified/Functor/Maybe.idr
Type checking ./Verified/Functor/List.idr
Type checking ./Verified/Functor/Vect.idr
./Verified/Functor/Vect.idr:5:10:
When elaborating type of Verified.Functor.Vect.Vect n instance of Verified.Functor.VerifiedFunctor:
When elaborating argument f to type constructor Verified.Functor.VerifiedFunctor:
        No such variable Vect
./Verified/Functor/Vect.idr:15:1:
No type declaration for Verified.Functor.Vect.lemma2
./Verified/Functor/Vect.idr:21:1:
No type declaration for Verified.Functor.Vect.lemma1
% idris --version
0.9.17.1-
% git describe --always
a598acd
```

**Comment by reynir** [comment]
Thanks for the report! It seems Vect was moved out of Prelude and into Data.Vect. It's now fixed, but there's a new error instead:

    ...
    ./Verified/Algebra/Bool.idr:11:10:VerifiedSemigroup is not a type class
    ./Verified/Algebra/Bool.idr:20:10:VerifiedMonoid is not a type class

It seems VerifiedSemigroup and VerifiedMonoid were removed as well! A fix would be to copy the (old) definition into the repo. I will take a look at it later when I have more time (PRs welcome! ;).

**Comment by reynir** [comment]
No, they've been moved to Classes.Verified!

**Comment by reynir** [comment]
It compiles again.
